mongo:
  image: mongo:latest
  volumes:
    - /home/vagrant/docker-data/mongo:/data/db
  ports:
    - "27017:27017"
mysql:
  image: mysql:latest
  volumes:
    - /home/vagrant/docker-data/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "mysqlpwd"
ubuntu:
  image: ubuntu:latest
