mongo:
  image: mongo:latest
  volumes:
    - /home/vagrant/docker-data/mongo:/data/db
  ports:
    - "27017:27017"
redis:
  image: redis:latest
  ports:
    - "6379:6379"
mysql:
  image: mysql:latest
  volumes:
    - /home/vagrant/docker-data/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "mysqlpwd"
postgres:
  image: postgres:9.4
  volumes:
    - /home/vagrant/docker-data/postgres:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: "mypostgrespwd"
nginx:
  restart: always
  image: jwilder/nginx-proxy:latest
  cpuset: "0"
  ports:
    - "80:80"
  volumes:
    - /home/vagrant/logs:/var/lib/nginxLogs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
