# Tomcat Server
# VERSION 0.0.1

# 基础镜像
FROM java:8-jre
# 维护者信息
MAINTAINER You Ming <xx@xxx.com>

# 安装Tomcat，并清理安装APT时产生的中间文件
RUN apt-get update && apt-get install -y tomcat8


# 对外暴露Tomcat使用的8080端口
EXPOSE 8080

# 启动命令，通过-g参数切换到前台运行
CMD ["/usr/share/tomcat8/bin/catalina.sh", "run"]