# MySQL
# VERSION 0.0.1

# 基础镜像
FROM debian:jessie
# 维护者信息
MAINTAINER You Ming <xx@xxx.com>

# 增加运行用户
 RUN groupadd -r mysql && useradd -r -g mysql mysql

# 增加安装源
RUN echo "deb http://repo.mysql.com/apt/debian/jessie mysql-5.7" > /etc/apt/sources.list.d/mysql.list \
    && apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5 \
    && apt-get update \
    && apt-get install -y --no-install-recommends perl pwgen

# 安装MySQL
RUN { \
# 设置MySQL用户密码
    echo mysql-community-server mysql-community-server/root-pass password ''; \
    echo mysql-community-server mysql-community-server/re-root-pass password ''; \
    } | debconf-set-selections \
    && apt-get install -y mysql-server="5.7.15-1debian8" \
    && mkdir -p /var/lib/mysql /var/run/mysql \
    && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
    && chmod 777 /var/run/mysqld



# 以数据卷的形式挂载MySQL存储数据的目录
VOLUME /var/lib/mysql

# 暴露MySQL的默认端口
EXPOSE 3306

# 启动MySQL
CMD ["mysqld", "--user", "mysql"]